version: "3.7"
services:

  generator-srv:
    build: './generator'
    container_name: generator-srv
    env_file:
      - './generator/.env'
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
      - localstack
      - generator-db
      - queue
  
  auth-srv:
    build: './auth'
    env_file:
      - './auth/.env'
    ports:
      - "5001:5001"
    depends_on:
      - auth-psql

  gateway-srv:
    build: './gateway'
    ports:
      - "5002:5002"
    depends_on:
      - localstack
  
  event-bus-srv:
    build: './event-bus'
    ports:
      - "5005:5005"

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  queue:
    build: './queue'
    user: nobody
    depends_on:
      - rabbit

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volumes/localstack-data}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  generator-db:
    image: mysql:latest
    container_name: generator-db
    ports:
      - "3306:3306"
    env_file:
      - './generator/.env'
    volumes:
      - ./volumes/mysql-data:/var/lib/mysql
    
  auth-psql:
    image: postgres:15-alpine
    container_name: auth-psql
    ports:
      - "5433:5432"
    env_file:
      - './auth/.env'
    volumes:
      - ./volumes/auth-psql-data:/var/lib/postgresql/data
      