version: "3.7"
services:

  generator-srv:
    build: './generator'
    env_file:
      - './generator/.env'
    ports:
      - "5000:5000"
    depends_on:
      - rabbit
      - localstack
      - generator-db
  
  event-bus-srv:
    build: './event-bus'
    ports:
      -"5005:5005"
    depends_on:
      - generator-srv

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  queue:
    build: './queue'
    user: nobody
    depends_on:
      - rabbit
      - generator-app

  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG-}
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
      
  generator-db:
    image: mysql:latest
    container_name: generator-db
    ports:
      - "3306:3306"
    env_file:
      - './generator/.env'
    volumes:
      - ./mysql-data:/var/lib/mysql