apiVersion: v1
kind: Service
metadata:
  name: generator-service
spec:
  selector:
    app: generator
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30001
      protocol: TCP