"""empty message

Revision ID: 04e34cf5403e
Revises: 
Create Date: 2023-05-24 23:57:50.310571

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04e34cf5403e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "certificate_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("certificate_number", sa.String(length=80), nullable=False),
        sa.Column("status", sa.String(length=120), nullable=True),
        sa.Column("s3_path", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("campaign_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("certificate_number"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("certificate_model")
    # ### end Alembic commands ###
